import type {
  ContentCategory,
  ContentMix,
  ContentTopic,
  RecommendationMode,
} from "./types";

export const DEFAULT_CONTENT_MIX: ContentMix = {
  health: 40,
  lifestyle: 20,
  ai_tech: 15,
  health_assets: 15,
  community: 10,
};

export const CATEGORY_META: Record<
  ContentCategory,
  { label: string; shortLabel: string; color: string }
> = {
  health: { label: "건강", shortLabel: "건강", color: "#10b981" },
  lifestyle: { label: "생활습관·라이프스타일", shortLabel: "생활습관", color: "#3b82f6" },
  ai_tech: { label: "AI·기술", shortLabel: "AI·기술", color: "#8b5cf6" },
  health_assets: { label: "돈·건강자산", shortLabel: "건강자산", color: "#f59e0b" },
  community: { label: "스토리·챌린지·커뮤니티", shortLabel: "커뮤니티", color: "#ec4899" },
};

export const MODE_META: Record<
  RecommendationMode,
  { label: string; description: string }
> = {
  balanced: { label: "균형 추천", description: "설정한 운영 비율에 맞춰 고르게 구성" },
  acquisition: { label: "신규 유입", description: "AI·생활·가족 등 확장 관심사를 우선" },
  conversion: { label: "건강진단 전환", description: "건강자산 체크로 이어지기 쉬운 주제" },
  shareable: { label: "공유 확산", description: "가족·친구와 나누기 좋은 참여형 주제" },
  brand: { label: "브랜드 구축", description: "건강자산과 건강통장 개념을 선명하게 전달" },
  seasonal: { label: "시즌 추천", description: "계절과 시기 반응도가 높은 주제" },
};

const topic = (
  value: Omit<ContentTopic, "recommendedChannels" | "recommendedFormats"> &
    Partial<Pick<ContentTopic, "recommendedChannels" | "recommendedFormats">>,
): ContentTopic => ({
  recommendedChannels: ["인스타그램", "블로그"],
  recommendedFormats: ["카드뉴스", "숏폼"],
  ...value,
});

export const DEFAULT_CONTENT_TOPICS: ContentTopic[] = [
  topic({
    id: "health-after-meal-sleepiness",
    title: "식후만 되면 집중력이 떨어지는 이유",
    interestCategory: "health",
    interestSubcategory: "혈당·에너지",
    healthAssetCodes: ["ENERGY", "BLOOD_SUGAR", "SLEEP", "BRAIN"],
    audienceProblem: "점심 식사 뒤 졸리고 업무 집중력이 떨어진다.",
    searchIntent: "정보 탐색",
    funnelStage: "awareness",
    contentPurpose: "문제 발견",
    ctaLevel: 2,
    recommendedCta: "나의 식후 에너지 상태 체크하기",
    evergreenScore: 94,
    seasonalityScore: 35,
    shareabilityScore: 82,
    conversionScore: 88,
  }),
  topic({
    id: "health-sleep-debt",
    title: "주말 몰아자기로 수면부채가 사라질까?",
    interestCategory: "health",
    interestSubcategory: "수면",
    healthAssetCodes: ["SLEEP", "ENERGY", "HORMONE"],
    audienceProblem: "평일 수면 부족을 주말에 보충하고 있다.",
    searchIntent: "오해 해소",
    funnelStage: "consideration",
    contentPurpose: "생활습관 점검",
    ctaLevel: 2,
    recommendedCta: "이번 주 수면 체크리스트 작성하기",
    evergreenScore: 92,
    seasonalityScore: 40,
    shareabilityScore: 78,
    conversionScore: 84,
  }),
  topic({
    id: "health-muscle-signals",
    title: "근육이 줄고 있다는 몸의 5가지 신호",
    interestCategory: "health",
    interestSubcategory: "근육·노화",
    healthAssetCodes: ["MUSCLE", "NUTRITION", "AGING"],
    audienceProblem: "예전보다 쉽게 지치고 계단이 부담스럽다.",
    searchIntent: "체크리스트",
    funnelStage: "conversion",
    contentPurpose: "자가 점검",
    ctaLevel: 3,
    recommendedCta: "나의 근육 건강자산 확인하기",
    evergreenScore: 96,
    seasonalityScore: 38,
    shareabilityScore: 90,
    conversionScore: 93,
  }),
  topic({
    id: "health-gut-immunity",
    title: "장 건강과 면역이 함께 움직이는 생활 신호",
    interestCategory: "health",
    interestSubcategory: "장건강·면역",
    healthAssetCodes: ["GUT", "IMMUNITY", "NUTRITION"],
    audienceProblem: "피로와 장 불편감이 자주 함께 나타난다.",
    searchIntent: "정보 탐색",
    funnelStage: "consideration",
    contentPurpose: "연결 이해",
    ctaLevel: 2,
    recommendedCta: "나의 장·면역 생활습관 점검하기",
    evergreenScore: 90,
    seasonalityScore: 70,
    shareabilityScore: 76,
    conversionScore: 86,
  }),
  topic({
    id: "health-10min-walk",
    title: "30분 운동이 부담스럽다면 10분씩 나누세요",
    interestCategory: "health",
    interestSubcategory: "운동",
    healthAssetCodes: ["CIRCULATION", "MUSCLE", "ENERGY"],
    audienceProblem: "운동할 시간을 따로 만들기 어렵다.",
    searchIntent: "실천 방법",
    funnelStage: "awareness",
    contentPurpose: "작은 행동",
    ctaLevel: 2,
    recommendedCta: "오늘 걷기 기록하기",
    evergreenScore: 95,
    seasonalityScore: 62,
    shareabilityScore: 86,
    conversionScore: 74,
  }),
  topic({
    id: "lifestyle-cafe-dessert",
    title: "카페에서 덜 피곤한 메뉴를 고르는 순서",
    interestCategory: "lifestyle",
    interestSubcategory: "외식",
    healthAssetCodes: ["BLOOD_SUGAR", "NUTRITION", "ENERGY"],
    audienceProblem: "카페 메뉴를 먹고 나면 쉽게 처진다.",
    searchIntent: "선택 가이드",
    funnelStage: "awareness",
    contentPurpose: "신규 유입",
    ctaLevel: 1,
    recommendedCta: "다음 카페 방문 때 한 가지만 적용해보기",
    evergreenScore: 88,
    seasonalityScore: 45,
    shareabilityScore: 91,
    conversionScore: 67,
    recommendedChannels: ["인스타그램", "Threads"],
    recommendedFormats: ["카드뉴스", "체크리스트"],
  }),
  topic({
    id: "lifestyle-travel-recovery",
    title: "장거리 여행에서 컨디션을 지키는 6가지 준비",
    interestCategory: "lifestyle",
    interestSubcategory: "여행",
    healthAssetCodes: ["SLEEP", "CIRCULATION", "NUTRITION"],
    audienceProblem: "여행만 다녀오면 회복에 며칠이 걸린다.",
    searchIntent: "준비 목록",
    funnelStage: "awareness",
    contentPurpose: "확장 유입",
    ctaLevel: 1,
    recommendedCta: "여행 전 체크리스트 저장하기",
    evergreenScore: 78,
    seasonalityScore: 92,
    shareabilityScore: 88,
    conversionScore: 62,
  }),
  topic({
    id: "lifestyle-work-routine",
    title: "시간관리보다 에너지관리가 먼저인 이유",
    interestCategory: "lifestyle",
    interestSubcategory: "생산성",
    healthAssetCodes: ["ENERGY", "SLEEP", "STRESS"],
    audienceProblem: "계획은 많지만 오후가 되면 실행력이 떨어진다.",
    searchIntent: "생산성 개선",
    funnelStage: "awareness",
    contentPurpose: "신규 유입",
    ctaLevel: 2,
    recommendedCta: "하루 에너지 흐름 체크하기",
    evergreenScore: 93,
    seasonalityScore: 40,
    shareabilityScore: 84,
    conversionScore: 79,
  }),
  topic({
    id: "lifestyle-parent-check",
    title: "부모님의 건강 변화를 확인하는 7가지 질문",
    interestCategory: "lifestyle",
    interestSubcategory: "가족",
    healthAssetCodes: ["MUSCLE", "CIRCULATION", "SLEEP", "AGING", "NUTRITION"],
    audienceProblem: "부모님의 작은 건강 변화를 놓칠까 걱정된다.",
    searchIntent: "체크리스트",
    funnelStage: "consideration",
    contentPurpose: "가족 참여",
    ctaLevel: 2,
    recommendedCta: "부모님께 건강체크 보내기",
    evergreenScore: 96,
    seasonalityScore: 58,
    shareabilityScore: 98,
    conversionScore: 85,
  }),
  topic({
    id: "ai-health-checkup",
    title: "건강검진 결과를 AI에게 질문하는 안전한 방법",
    interestCategory: "ai_tech",
    interestSubcategory: "ChatGPT 건강 활용",
    healthAssetCodes: ["HEALTH_LITERACY"],
    audienceProblem: "검진 수치를 이해하고 싶지만 무엇부터 물을지 모르겠다.",
    searchIntent: "AI 활용법",
    funnelStage: "awareness",
    contentPurpose: "신규 유입",
    ctaLevel: 1,
    recommendedCta: "질문 프롬프트 저장하기",
    evergreenScore: 91,
    seasonalityScore: 50,
    shareabilityScore: 92,
    conversionScore: 70,
    recommendedChannels: ["블로그", "유튜브"],
    recommendedFormats: ["블로그", "튜토리얼"],
  }),
  topic({
    id: "ai-wearable-sleep",
    title: "스마트워치 수면점수, 어디까지 믿어야 할까?",
    interestCategory: "ai_tech",
    interestSubcategory: "웨어러블",
    healthAssetCodes: ["SLEEP", "AUTONOMIC_NERVOUS_SYSTEM"],
    audienceProblem: "기기마다 다른 수면점수 때문에 혼란스럽다.",
    searchIntent: "데이터 해석",
    funnelStage: "consideration",
    contentPurpose: "건강데이터 이해",
    ctaLevel: 3,
    recommendedCta: "나의 수면자산 함께 확인하기",
    evergreenScore: 86,
    seasonalityScore: 48,
    shareabilityScore: 83,
    conversionScore: 88,
  }),
  topic({
    id: "ai-personal-health-data",
    title: "AI 건강코치에게 맡겨도 되는 데이터와 안 되는 데이터",
    interestCategory: "ai_tech",
    interestSubcategory: "AI 건강관리",
    healthAssetCodes: ["HEALTH_LITERACY", "PRIVACY"],
    audienceProblem: "개인 건강데이터의 안전한 활용 범위를 알고 싶다.",
    searchIntent: "비교·판단",
    funnelStage: "consideration",
    contentPurpose: "신뢰 형성",
    ctaLevel: 1,
    recommendedCta: "건강데이터 안전수칙 저장하기",
    evergreenScore: 89,
    seasonalityScore: 44,
    shareabilityScore: 79,
    conversionScore: 64,
  }),
  topic({
    id: "asset-health-compound",
    title: "건강도 복리로 쌓인다는 말의 진짜 의미",
    interestCategory: "health_assets",
    interestSubcategory: "건강자산 개념",
    healthAssetCodes: ["TOTAL_HEALTH_ASSET"],
    audienceProblem: "작은 건강습관이 정말 의미가 있는지 확신이 없다.",
    searchIntent: "개념 이해",
    funnelStage: "consideration",
    contentPurpose: "브랜드 교육",
    ctaLevel: 3,
    recommendedCta: "현재 건강자산 점수 확인하기",
    evergreenScore: 98,
    seasonalityScore: 30,
    shareabilityScore: 87,
    conversionScore: 96,
  }),
  topic({
    id: "asset-health-debt",
    title: "건강부채는 무엇이며 언제부터 갚아야 할까?",
    interestCategory: "health_assets",
    interestSubcategory: "건강자산 개념",
    healthAssetCodes: ["TOTAL_HEALTH_ASSET", "RISK"],
    audienceProblem: "당장 아프지 않아 건강관리를 미루고 있다.",
    searchIntent: "문제 인식",
    funnelStage: "conversion",
    contentPurpose: "전환",
    ctaLevel: 3,
    recommendedCta: "나의 건강부채 신호 확인하기",
    evergreenScore: 97,
    seasonalityScore: 32,
    shareabilityScore: 84,
    conversionScore: 99,
  }),
  topic({
    id: "asset-daily-stack",
    title: "오늘 건강통장에 무엇을 입금하셨나요?",
    interestCategory: "health_assets",
    interestSubcategory: "건강통장",
    healthAssetCodes: ["TOTAL_HEALTH_ASSET"],
    audienceProblem: "건강 행동을 꾸준히 기록할 동기가 부족하다.",
    searchIntent: "참여",
    funnelStage: "relationship",
    contentPurpose: "브랜드 습관화",
    ctaLevel: 2,
    recommendedCta: "오늘의 건강 STACK 기록하기",
    evergreenScore: 94,
    seasonalityScore: 35,
    shareabilityScore: 93,
    conversionScore: 90,
  }),
  topic({
    id: "community-water-7days",
    title: "7일 물 마시기 챌린지",
    interestCategory: "community",
    interestSubcategory: "챌린지",
    healthAssetCodes: ["HYDRATION", "ENERGY"],
    audienceProblem: "물을 챙겨 마시는 습관이 잘 만들어지지 않는다.",
    searchIntent: "참여",
    funnelStage: "relationship",
    contentPurpose: "가벼운 참여",
    ctaLevel: 2,
    recommendedCta: "7일 미션 시작하기",
    evergreenScore: 88,
    seasonalityScore: 82,
    shareabilityScore: 97,
    conversionScore: 68,
    recommendedChannels: ["인스타그램", "카카오톡"],
    recommendedFormats: ["챌린지", "공유 카드"],
  }),
  topic({
    id: "community-family-mission",
    title: "이번 주 가족 건강미션: 저녁 산책 3회",
    interestCategory: "community",
    interestSubcategory: "가족 미션",
    healthAssetCodes: ["CIRCULATION", "MUSCLE", "FAMILY"],
    audienceProblem: "가족과 함께할 수 있는 쉬운 건강활동이 필요하다.",
    searchIntent: "참여",
    funnelStage: "relationship",
    contentPurpose: "관계 형성",
    ctaLevel: 4,
    recommendedCta: "가족 건강그룹 만들기",
    evergreenScore: 90,
    seasonalityScore: 68,
    shareabilityScore: 99,
    conversionScore: 80,
  }),
  topic({
    id: "community-four-week-story",
    title: "4주 동안 건강통장을 기록하면 달라지는 것",
    interestCategory: "community",
    interestSubcategory: "변화 스토리",
    healthAssetCodes: ["TOTAL_HEALTH_ASSET"],
    audienceProblem: "건강 기록의 효과를 실제 변화 흐름으로 보고 싶다.",
    searchIntent: "경험 탐색",
    funnelStage: "conversion",
    contentPurpose: "사회적 증거",
    ctaLevel: 4,
    recommendedCta: "4주 건강자산 프로그램 시작하기",
    evergreenScore: 91,
    seasonalityScore: 45,
    shareabilityScore: 95,
    conversionScore: 94,
  }),
];

